### ISSUE TITLE
Curious case of lack of DEPENDENCIES_STR being created...

### ISSUE THREAD

**Issue by marcb** [lukaslueg/built#1]
Built doesn't seem to be producing `DEPENDENCIES_STR` & `DEPENDENCIES` from the `Cargo.lock` file.

```
error[E0425]: cannot find value `DEPENDENCIES_STR` in module `built_info`
  --> src/main.rs:24:25
   |
24 |             built_info::DEPENDENCIES_STR);
   |                         ^^^^^^^^^^^^^^^^ not found in `built_info`
```

I'm curious what circumstances would lead to that?

**Comment by lukaslueg** [comment]
Because only binaries get to "own" a `Cargo.lock` (it's never generated for libraries being built a dependencies), you'll have to [set](https://lukaslueg.github.io/built/built/struct.Options.html#method.set_dependencies) `Options::set_dependencies(true)` explicitly.

**Comment by marcb** [comment]
Thanks! That worked for by app.
