### ISSUE TITLE
"Writes rust-code describing the crate at src to a new file named dst."

### ISSUE THREAD

**Issue by xftroxgpx** [lukaslueg/built#11]
> Writes rust-code describing the crate at `src` to a new file named `dst`.

What does `src` refer to in [this](https://docs.rs/built/0.2.3/built/fn.write_built_file_with_opts.html) context ?
Was it a field at one time, but not anymore?

**Comment by xftroxgpx** [comment]
oh is `src` actually `manifest_location` ?

**Comment by lukaslueg** [comment]
Yes, the docs are actually off, it should be

> Writes rust-code describing the crate at `manifest_location` to a new file named `dst`

**Comment by xftroxgpx** [comment]
Should I make a PR for that? ;)
