### ISSUE TITLE
write_built_file_with_opts with the same P & Q as write_built_file

### ISSUE THREAD

**Issue by xftroxgpx** [lukaslueg/built#12]
Can we get a `write_built_file_with_opts` function with the same `P` & `Q` as `write_built_file` ?

manifest_location: P, 
    dst: Q
https://docs.rs/built/0.2.3/built/fn.write_built_file_with_opts.html

A shorthand for calling write_built_file() with `CARGO_MANIFEST_DIR` and `[OUT_DIR]/built.rs`.
https://docs.rs/built/0.2.3/built/fn.write_built_file.html

If yes, I could try a PR, though I am very beginner, but I believe I can manage it :D

**EDIT:** brb while I try to reconcile the fact that Rust doesn't support two functions with the same name but different amount of args (according to people on irc, at least)
**EDIT2:** [Builder pattern](https://github.com/rust-unofficial/patterns/blob/master/patterns/builder.md) hmmm... 
**EDIT3:** ok i don't like it, so nevermind... closing issue :D 
**EDIT4:** actually I'm intrigued and kinda interested how would one go about implementing this very case; for learning purposes. (re-openning)

**Comment by xftroxgpx** [comment]
Ok, so basically, we have:
`write_built_file_with_opts` with 3 args https://docs.rs/built/0.2.3/src/built/lib.rs.html#766-821
and
`write_built_file` with no args https://docs.rs/built/0.2.3/src/built/lib.rs.html#825-830

Wanted:
`write_built_file_with_opts` with 1 arg (the `options: &Options` one)
or
what other solution ? other than using a new name for the function.

**Comment by lukaslueg** [comment]
I don't think we need a variant with one argument. The one with three args gives all the options and the one without any reflects the most simple case. An additional variant only increases documentation burden for the user.

`write_built_file()` has v[ery simple defaults](https://github.com/lukaslueg/built/blob/master/src/lib.rs#L810) that one can mimick.

**Comment by xftroxgpx** [comment]
You're right, we don't need that. But would've been interesting to see how we would've gone about implementing that, assuming we wanted it.

Thanks either way:)

**Comment by lukaslueg** [comment]
Rust does not have default argument values (for good reasons I think). You may want to take a look at [this](https://github.com/lukaslueg/built/blob/master/tests/testbox_tests.rs#L18) regarding the Builder-pattern: Have a struct, set some options that deviate from the struct's defaults and then call some method on it that consumes the struct and produces what you want (in this case `create()`). Most likely there is a proc-macro-crate for this.
