### ISSUE TITLE
Optimisation level might not be an integer

### ISSUE THREAD

**Issue by adamgreig** [lukaslueg/built#15]
Currently `OPT_LEVEL` has type `u8` but if it's set to `s` or `z` then the generated built.rs won't build:

```
   |
35 | pub const OPT_LEVEL: u8 = z;
   |                           ^ not found in this scope
```

Maybe it should be a string instead?

**Comment by lukaslueg** [comment]
In fact it should. We'll have to bump version numbers to 0.3. Can you do a PR?
