### ISSUE TITLE
Does not handle opt-level = "s"

### ISSUE THREAD

**Issue by whitequark** [lukaslueg/built#17]
This is a valid Cargo.toml profile:
```
[profile.release]
opt-level = "s"
```
But, built generates invalid code for it:
```
   |
35 | pub const OPT_LEVEL: u8 = s;
   |                           ^ not found in this scope
```

**Comment by lukaslueg** [comment]
Yeah, I knew the `u8` would someday come back. Would you do a PR on this ?

**Comment by whitequark** [comment]
Probably not, I don't use built, I discovered this by accident investigating someone else's code.

**Comment by lukaslueg** [comment]
Ok, thanks for the heads-up!

**Comment by lukaslueg** [comment]
Oh look, this was [fixed](https://github.com/lukaslueg/built/issues/15) in 0.3
