### ISSUE TITLE
Suggestion: incorporate information from cfg

### ISSUE THREAD

**Issue by PhilipDaniels** [lukaslueg/built#2]
The `target_info` crate, which consists of just one file - https://github.com/gavofyork/target_info/blob/master/src/lib.rs - does similar things. It would be nice to incorporate its code into `built` so we can get a full set of constants.  

See also here https://doc.rust-lang.org/reference/attributes.html#conditional-compilation

**Comment by lukaslueg** [comment]
I'm unsure about the value of this information; I see no further use than eyecandy. People should use proper `cfg`-attributes to steer code paths that differ per platform and not rely on comparing variables. 

Note that built already [includes](https://docs.rs/built/0.1.0/built/struct.Options.html#method.set_env) `TARGET`, which comes out as something like "x86_64-apple-darwin" or similar.

**Comment by PhilipDaniels** [comment]
I'm looking to build a program which will incorporate a scripting language layer and knowing this stuff would be useful.

**Comment by lukaslueg** [comment]
The latest `master` provides the `cfg!()`-attributes. Please review if this fits your needs.

**Comment by PhilipDaniels** [comment]
Thanks, I pulled the master version and it looks good as regards the cfg info.

One observation, some of the generated constants use #doc attributes while some use triple slashes. I don't know enough about Rust to know if it matters.

```
#[doc="Value of DEBUG for the profile used during compilation."]
pub const DEBUG: bool = true;
/// The features that were enabled during compilation.
pub const FEATURES: [&'static str; 0] = [];
```

**Comment by lukaslueg** [comment]
This is due to some of the code being generated by macros and the docstrings being passed through those. I can't remember the details, but there was a problem with either of two methods.

**Comment by lukaslueg** [comment]
If you are good with this, I can push a new version to `crates.io`

**Comment by PhilipDaniels** [comment]
It's working for me, go ahead and publish a new version, thanks for the quick response.

**Comment by lukaslueg** [comment]
I've pushed `0.2.0` which has the `cfg!` features
