### ISSUE TITLE
Paths containing backslashes can cause build failures

### ISSUE THREAD

**Issue by tari** [lukaslueg/built#27]
For instance on Windows (where this is almost certain to happen):

```
error: unknown character escape: P
  --> C:\...\out/built.rs:31:29
   |
31 | pub const RUSTC: &str = "C:\ProgramData\chocolatey\bin\rustc.exe";
   |                             ^ unknown character escape
```

This should be easily fixable by emitting raw strings so backslashes don't get interpreted in the strings that get written out.

**Comment by lukaslueg** [comment]
Hmm, I wonder why this is not picked up on AppVeyor, where `RUSTC` is in "C:\Users\appveyor\.cargo\bin"
