### ISSUE TITLE
Version 0.5.3 isn't backward compatible

### ISSUE THREAD

**Issue by r-bk** [lukaslueg/built#51]
Version `0.5.3` includes commit `17279871f75e6bb395dfc7bcfd8b04cdc8bfe061` which changes the function `util::get_repo_head` to return a 3-tuple, while it was a 2-tuple in version `0.5.2`. This change isn't backward compatible, and thus shouldn't be released in a bug-fix release, to not break existing user code which relies on the return value of this function.

The current situation is that a crate that uses this function doesn't compile just because `0.5.3` was released, and `cargo` is free to auto-upgrade to this version if built is specified in `Cargo.toml` as `built = "0.5.1"`, for example.

**Comment by lukaslueg** [comment]
Thanks for the heads-up. I yanked `0.5.3` and will re-release `0.5.3` as `0.6.0` later on.

`cargo semver-checks` didn't catch this because the `util::get_repo_head` function is behind the `git2` feature...

**Comment by lukaslueg** [comment]
Closed by yanking `0.5.3` and re-releasing as `0.6.0`
