### ISSUE TITLE
Add support for SOURCE_DATE_EPOCH

### ISSUE THREAD

**Issue by internet-catte** [lukaslueg/built#67]
For reproducibility, `BUILT_TIME_UTC` should be overridden by the [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) environment variable. This is useful when building crates that use `built` in an environment like a Linux distro's package build system.

**Comment by lukaslueg** [comment]
Seems easy enough. I'd be inclined to unconditionally use `SOURCE_DATE_EPOCH` over local time, if defined at all, and `panic!` if parsing fails. Is there a scenario where this would be wrong?
