### ISSUE TITLE
Support for Cargo.lock format version 4

### ISSUE THREAD

**Issue by joamag** [lukaslueg/built#71]
I'm getting compilation errors in Rust nightly due to the built's lack of support for the new Cargo.lock version 4.

```
Caused by:
  process didn't exit successfully: `/.../build/boytacean-d1602522edb07f70/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/built-0.7.4/src/dependencies.rs:151:59:
  Failed to parse lockfile: Parse("parse error: invalid Cargo.lock format version: `4`\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by lukaslueg** [comment]
Thanks for the heads-up. This is due to https://github.com/rust-lang/cargo/pull/14595. We use `cargo-audit`'s parser for `Cargo.lock`-files, the switch to v4 is tracked in https://github.com/rustsec/rustsec/issues/1249.

**Comment by tarcieri** [comment]
Open PR here. Feedback appreciated: https://github.com/rustsec/rustsec/pull/1206
