### ISSUE TITLE
Consider using env. variables

### ISSUE THREAD

**Issue by Xion** [lukaslueg/built#8]
Since some time, there is an option to output `cargo:rustc-env=FOO=BAR` lines from build.rs. This causes an environment variable `FOO` to be set to the value of `BAR` for the invocation of rustc, making it readable with `env!()` etc.

This seems like a good vehicle for carrying build-time information for `built`. (I'm using it myself for including the Git SHA, for example).

**Comment by lukaslueg** [comment]
I'm sorry, what do you propose?

**Comment by Xion** [comment]
After looking at the code a little bit more, I think your approach is actually better since it immediately creates Rust structures that can be accessed by the crate's code. If you were to carry the build information in env. variables, there would be an additional decoding step which would carry a (small) runtime overhead.

Carry on :)
